import type { TypographyToken } from "../types";

const display = "[font-family:var(--font-display)] font-medium text-gray-950";
const headingSerif =
  "[font-family:var(--font-display)] font-semibold text-gray-950";

export const typographyTokens: TypographyToken[] = [
  {
    name: "Display/2XL",
    fontFamily: "Georgia",
    fontRole: "display",
    sizePx: 48,
    lineHeightPx: 56,
    weight: 500,
    tracking: "-0.02em",
    colorRole: "text/primary",
    usage: "Hero and splash moments.",
    avoid: "Do not use inside controls, tables, or dense status flows.",
    className: `text-[48px] leading-[56px] tracking-[-0.02em] ${display}`,
    status: "stable",
  },
  {
    name: "Display/XL",
    fontFamily: "Georgia",
    fontRole: "display",
    sizePx: 40,
    lineHeightPx: 48,
    weight: 500,
    tracking: "-0.02em",
    colorRole: "text/primary",
    usage: "Large page titles.",
    avoid: "Avoid in checkout, payment, and status rows.",
    className: `text-[40px] leading-[48px] tracking-[-0.02em] ${display}`,
    status: "stable",
  },
  {
    name: "Display/L",
    fontFamily: "Georgia",
    fontRole: "display",
    sizePx: 36,
    lineHeightPx: 44,
    weight: 500,
    tracking: "-0.01em",
    colorRole: "text/primary",
    usage: "Major section titles and expressive empty states.",
    avoid: "Avoid in compact cards.",
    className: `text-[36px] leading-[44px] tracking-[-0.01em] ${display}`,
    status: "stable",
  },
  {
    name: "Display/M",
    fontFamily: "Georgia",
    fontRole: "display",
    sizePx: 30,
    lineHeightPx: 38,
    weight: 500,
    tracking: "-0.01em",
    colorRole: "text/primary",
    usage: "Prominent section headings.",
    avoid: "Avoid for repeated list items.",
    className: `text-[30px] leading-[38px] tracking-[-0.01em] ${display}`,
    status: "stable",
  },
  {
    name: "Heading/L",
    fontFamily: "Georgia",
    fontRole: "display",
    sizePx: 24,
    lineHeightPx: 32,
    weight: 600,
    tracking: "-0.01em",
    colorRole: "text/primary",
    usage: "Expressive page and sheet title moments.",
    avoid: "Avoid in checkout, payment, and status flows.",
    className: `text-2xl leading-8 tracking-[-0.01em] ${headingSerif}`,
    status: "stable",
  },
  {
    name: "Heading/M",
    fontFamily: "Georgia",
    fontRole: "display",
    sizePx: 22,
    lineHeightPx: 28,
    weight: 500,
    tracking: "-0.01em",
    colorRole: "text/primary",
    usage: "Operational subsection titles.",
    avoid: "Avoid for body copy.",
    className: `text-[22px] leading-7 tracking-[-0.01em] ${display}`,
    status: "stable",
  },
  {
    name: "Heading/S",
    fontFamily: "Georgia",
    fontRole: "display",
    sizePx: 18,
    lineHeightPx: 26,
    weight: 500,
    tracking: "0",
    colorRole: "text/primary",
    usage: "Diner section headings and lower-emphasis expressive titles.",
    avoid: "Avoid using serif in payment/status labels.",
    className: `text-lg leading-[26px] ${display}`,
    status: "stable",
  },
  {
    name: "Heading/XS",
    fontFamily: "Geist Sans",
    fontRole: "body",
    sizePx: 16,
    lineHeightPx: 24,
    weight: 600,
    tracking: "0",
    colorRole: "text/primary",
    usage: "Item names and minor headings.",
    avoid: "Avoid for paragraphs.",
    className: "text-base font-semibold leading-6 text-gray-950",
    status: "stable",
  },
  {
    name: "Body/L",
    fontFamily: "Geist Sans",
    fontRole: "body",
    sizePx: 16,
    lineHeightPx: 24,
    weight: 400,
    tracking: "0",
    colorRole: "text/secondary",
    usage: "Long-form descriptions.",
    avoid: "Avoid for labels or buttons.",
    className: "text-base font-normal leading-6 text-gray-600",
    status: "stable",
  },
  {
    name: "Body/M",
    fontFamily: "Geist Sans",
    fontRole: "body",
    sizePx: 14,
    lineHeightPx: 22,
    weight: 400,
    tracking: "0",
    colorRole: "text/secondary",
    usage: "Standard body text.",
    avoid: "Avoid for prices.",
    className: "text-sm font-normal leading-[22px] text-gray-600",
    status: "stable",
  },
  {
    name: "Body/S",
    fontFamily: "Geist Sans",
    fontRole: "body",
    sizePx: 13,
    lineHeightPx: 20,
    weight: 400,
    tracking: "0.01em",
    colorRole: "text/tertiary",
    usage: "Secondary descriptions.",
    avoid: "Avoid for required information.",
    className:
      "text-[13px] font-normal leading-5 tracking-[0.01em] text-gray-500",
    status: "stable",
  },
  {
    name: "Label/L",
    fontFamily: "Geist Sans",
    fontRole: "utility",
    sizePx: 14,
    lineHeightPx: 20,
    weight: 500,
    tracking: "0.01em",
    colorRole: "text/primary",
    usage: "Form labels and tab labels.",
    avoid: "Avoid for paragraphs.",
    className: "text-sm font-medium leading-5 tracking-[0.01em] text-gray-950",
    status: "stable",
  },
  {
    name: "Label/M",
    fontFamily: "Geist Sans",
    fontRole: "utility",
    sizePx: 13,
    lineHeightPx: 18,
    weight: 500,
    tracking: "0.01em",
    colorRole: "text/secondary",
    usage: "Metadata and badge text.",
    avoid: "Avoid for prices.",
    className:
      "text-[13px] font-medium leading-[18px] tracking-[0.01em] text-gray-600",
    status: "stable",
  },
  {
    name: "Label/S",
    fontFamily: "Geist Sans",
    fontRole: "utility",
    sizePx: 12,
    lineHeightPx: 16,
    weight: 500,
    tracking: "0.02em",
    colorRole: "text/tertiary",
    usage: "Small labels and chip text.",
    avoid: "Avoid for long labels.",
    className: "text-xs font-medium leading-4 tracking-[0.02em] text-gray-500",
    status: "stable",
  },
  {
    name: "Utility/L",
    fontFamily: "Geist Sans",
    fontRole: "utility",
    sizePx: 14,
    lineHeightPx: 20,
    weight: 500,
    tracking: "0.02em",
    colorRole: "text/primary",
    numeric: true,
    usage: "Prices and totals.",
    avoid: "Avoid proportional numbers.",
    className:
      "text-sm font-medium leading-5 tracking-[0.02em] text-gray-950 tabular-nums",
    status: "stable",
  },
  {
    name: "Utility/M",
    fontFamily: "Geist Sans",
    fontRole: "utility",
    sizePx: 13,
    lineHeightPx: 18,
    weight: 500,
    tracking: "0.02em",
    colorRole: "text/secondary",
    numeric: true,
    usage: "Quantity and compact prices.",
    avoid: "Avoid for section headings.",
    className:
      "text-[13px] font-medium leading-[18px] tracking-[0.02em] text-gray-600 tabular-nums",
    status: "stable",
  },
  {
    name: "Utility/S",
    fontFamily: "Geist Sans",
    fontRole: "utility",
    sizePx: 11,
    lineHeightPx: 16,
    weight: 500,
    tracking: "0.03em",
    colorRole: "text/tertiary",
    numeric: true,
    usage: "Timestamps, helper text, and captions.",
    avoid: "Avoid for primary actions.",
    className:
      "text-[11px] font-medium leading-4 tracking-[0.03em] text-gray-500 tabular-nums",
    status: "stable",
  },
];

export const typographyStyles = typographyTokens.map((token) => ({
  surface: "diner-ordering" as const,
  group: token.name.split("/")[0] as
    | "Display"
    | "Heading"
    | "Body"
    | "Label"
    | "Utility",
  name: token.name,
  fontFamily: token.fontFamily,
  fontRole: token.fontRole,
  size: `${token.sizePx}px`,
  lineHeight: `${token.lineHeightPx}px`,
  weight: `${token.weight}`,
  tracking: token.tracking,
  colorRole: token.colorRole,
  numeric: token.numeric ? ("tabular" as const) : ("normal" as const),
  usage: token.usage,
  avoid: token.avoid ?? "Avoid undocumented use.",
  className: token.className ?? "",
  status: token.status,
}));
