import type { ComponentVariant } from "../types";

export const cardComponentVariants: ComponentVariant[] = [
  {
    component: "MenuItemCard",
    variant: "default",
    group: "Cards",
    surface: "diner-ordering",
    states: ["default", "hover", "focus-visible", "unavailable"],
    tokensUsed: [
      "radius/item-card",
      "surface/card",
      "border/subtle",
      "shadow/none",
    ],
    anatomy: [
      "Image/fallback",
      "Item name",
      "Description",
      "Price",
      "Add affordance",
    ],
    accessibility: ["Card action announces item name, price, and availability"],
    usage: "Menu browsing and category lists.",
    avoid: "Avoid default shadows; cards are border-first.",
    exampleClassName: "rounded-2xl border border-gray-100 bg-white p-4",
    status: "stable",
  },
  {
    component: "ItemCard",
    variant: "cart-order-bill",
    group: "Cards",
    surface: "diner-ordering",
    states: ["default", "selected", "disabled", "unavailable"],
    tokensUsed: ["radius/item-card", "Utility/L", "Heading/XS", "Body/S"],
    anatomy: ["Title", "Modifiers/status", "Price", "Quantity/status control"],
    accessibility: ["Selection state must not rely on color alone"],
    usage: "Cart rows, order rows, split bill item rows, and bill lines.",
    avoid: "Avoid changing card family styling by screen.",
    status: "stable",
  },
  {
    component: "BillSummary",
    variant: "totals",
    group: "Cards",
    surface: "diner-ordering",
    states: ["default"],
    tokensUsed: ["radius/card", "Utility/L", "Utility/M", "border/subtle"],
    anatomy: ["Subtotal row", "Tax/service rows", "Total row"],
    accessibility: ["Totals must be text-readable and use tabular numbers"],
    usage: "Cart, bill, payment, and split bill summaries.",
    avoid: "Avoid hiding fees in muted tiny text.",
    exampleClassName: "rounded-xl border border-gray-100 bg-white p-4",
    status: "stable",
  },
  {
    component: "Payment Card",
    variant: "method",
    group: "Cards",
    surface: "diner-ordering",
    states: ["default", "selected", "disabled", "error"],
    tokensUsed: [
      "radius/card",
      "border/default",
      "action/primary",
      "state/info",
    ],
    anatomy: [
      "Method title",
      "Helper text",
      "Selected marker",
      "Optional instruction",
    ],
    accessibility: [
      "Use radio semantics for mutually exclusive payment methods",
    ],
    usage: "Transfer, card, cash, split modes, and payment prompts.",
    avoid: "Avoid visually unrelated payment cards.",
    status: "stable",
  },
];
