import type { ComponentVariant } from "../types";

export const feedbackComponentVariants: ComponentVariant[] = [
  {
    component: "Badge",
    variant: "status",
    group: "Feedback",
    surface: "diner-ordering",
    intent: "neutral",
    states: ["default", "selected", "disabled"],
    tokensUsed: [
      "radius/chip",
      "Label/S",
      "state/success",
      "state/warning",
      "state/danger",
    ],
    anatomy: ["Pill", "Short text", "Optional icon/dot"],
    accessibility: ["State must be readable as text, not color only"],
    usage:
      "Required, popular, new, unavailable, preparing, ready, served, paid.",
    avoid: "Avoid purely decorative badges.",
    exampleClassName: "rounded-full border border-gray-200 px-2 py-1 text-xs",
    status: "stable",
  },
  {
    component: "OrderStatusTimeline",
    variant: "compact",
    group: "Feedback",
    surface: "diner-ordering",
    states: ["default", "selected", "disabled"],
    tokensUsed: ["state/success", "state/warning", "Body/S", "Label/M"],
    anatomy: ["Aligned dot", "Connector", "Status label", "Supporting text"],
    accessibility: ["Completed/current/upcoming must have text labels"],
    usage: "Live order and order status sheet.",
    avoid: "Avoid oversized dots or stretched vertical gaps.",
    status: "stable",
  },
  {
    component: "Alert / Toast",
    variant: "status",
    group: "Feedback",
    surface: "diner-ordering",
    intent: "info",
    states: ["default", "error"],
    tokensUsed: ["state/info", "state/success", "state/danger", "radius/card"],
    anatomy: ["Icon", "Title", "Description", "Optional action", "Dismiss"],
    accessibility: [
      "Use live regions where appropriate",
      "Errors need recovery actions",
    ],
    usage: "Added to cart, copy success, network error, payment failure.",
    avoid: "Avoid auto-dismissing payment/order errors too quickly.",
    status: "stable",
  },
  {
    component: "Empty / Loading / Error State",
    variant: "diner",
    group: "Feedback",
    surface: "diner-ordering",
    states: ["empty", "loading", "error"],
    tokensUsed: ["surface/muted", "Body/M", "Button"],
    anatomy: ["Icon/illustration", "Message", "Guidance", "Optional retry CTA"],
    accessibility: ["Loading regions use aria-busy", "Errors are announced"],
    usage: "Empty cart, empty category, loading menu, network error.",
    avoid: "Avoid blank screens or spinner-only loading states.",
    status: "stable",
  },
];
