import type { ComponentCoverage, ComponentVariant } from "../types";

export const flowComponentVariants: ComponentVariant[] = [
  {
    component: "Fixed CTA Footer",
    variant: "summary-action",
    group: "Flow",
    surface: "diner-ordering",
    states: ["default", "disabled", "loading"],
    tokensUsed: [
      "z/fixed-footer",
      "shadow/floating",
      "layout/mobile-safe-area-bottom",
    ],
    anatomy: [
      "White footer",
      "Top border",
      "Optional stepper/summary",
      "Primary CTA",
    ],
    accessibility: [
      "Footer controls must be keyboard reachable",
      "Disabled state must be announced",
    ],
    usage: "Add to cart, checkout, request bill, payment, split bill.",
    avoid: "Avoid covering content without footer offset.",
    exampleClassName:
      "border-t border-gray-100 bg-white p-4 shadow-[0_8px_24px_rgba(0,0,0,0.12)]",
    status: "stable",
  },
  {
    component: "DinerShell",
    variant: "phone-shell",
    group: "Flow",
    surface: "diner-ordering",
    states: ["default"],
    tokensUsed: [
      "layout/diner-content-max",
      "surface/page",
      "space/page-gutter",
    ],
    anatomy: [
      "Centered mobile shell",
      "Page background",
      "Scrollable content",
      "Safe footer space",
    ],
    accessibility: ["Use main landmark for diner content"],
    usage: "Top-level guest ordering shell.",
    avoid: "Avoid wide dashboard layouts inside diner flow.",
    status: "stable",
  },
  {
    component: "CartScreen",
    variant: "checkout-flow",
    group: "Flow",
    surface: "diner-ordering",
    states: ["default", "empty", "loading"],
    tokensUsed: [
      "ItemCard",
      "BillSummary",
      "DinerTextarea",
      "Fixed CTA Footer",
    ],
    anatomy: [
      "Header",
      "Cart item list",
      "Kitchen note",
      "Summary",
      "Checkout CTA",
    ],
    accessibility: ["Quantity changes should be announced when possible"],
    usage: "Review cart and place order.",
    avoid: "Avoid changing item-card family inside cart.",
    status: "stable",
  },
  {
    component: "BillView",
    variant: "payment-flow",
    group: "Flow",
    surface: "diner-ordering",
    states: ["default", "selected", "loading", "error"],
    tokensUsed: [
      "BillSummary",
      "Payment Card",
      "SegmentedTabs",
      "Fixed CTA Footer",
    ],
    anatomy: [
      "Receipt summary",
      "Payment methods",
      "Tip/loyalty",
      "Payment CTA",
    ],
    accessibility: ["Payment errors must include text and recovery action"],
    usage: "Bill review and payment.",
    avoid: "Avoid decorative color in payment-critical copy.",
    status: "stable",
  },
  {
    component: "SplitPartPage",
    variant: "participant-payment",
    group: "Flow",
    surface: "diner-ordering",
    states: ["default", "selected", "error"],
    tokensUsed: ["Payment Card", "ItemCard", "BillSummary"],
    anatomy: [
      "Participant status",
      "Assigned items",
      "Amount due",
      "Payment CTA",
    ],
    accessibility: ["Paid/unpaid status must be text-backed"],
    usage: "Participant-facing split bill payment.",
    avoid: "Avoid color-only paid/unpaid states.",
    status: "stable",
  },
];

export const componentCoverage: ComponentCoverage[] = [
  [
    "BottomSheet",
    "components/diner/ui/BottomSheet.tsx",
    "primitive",
    true,
    true,
    "covered",
    "Reusable sheet primitive.",
  ],
  [
    "DinerInput",
    "components/diner/ui/DinerInput.tsx",
    "primitive",
    true,
    true,
    "covered",
    "Input primitive.",
  ],
  [
    "DinerTextarea",
    "components/diner/ui/DinerTextarea.tsx",
    "primitive",
    true,
    true,
    "covered",
    "Textarea primitive.",
  ],
  [
    "SegmentedTabs",
    "components/diner/ui/SegmentedTabs.tsx",
    "primitive",
    true,
    true,
    "covered",
    "Segmented navigation/control primitive.",
  ],
  [
    "PageHeader",
    "components/diner/ui/PageHeader.tsx",
    "primitive",
    true,
    true,
    "covered",
    "Reusable page header.",
  ],
  [
    "BillSummary",
    "components/diner/ui/BillSummary.tsx",
    "visual",
    true,
    true,
    "covered",
    "Totals card.",
  ],
  [
    "ItemCard",
    "components/diner/ui/ItemCard.tsx",
    "visual",
    true,
    true,
    "covered",
    "Shared item card family.",
  ],
  [
    "OrderStatusTimeline",
    "components/diner/ui/OrderStatusTimeline.tsx",
    "visual",
    true,
    true,
    "covered",
    "Compact timeline.",
  ],
  [
    "MenuItemCard",
    "components/diner/MenuItemCard.tsx",
    "visual",
    true,
    true,
    "covered",
    "Menu item variant.",
  ],
  [
    "ItemDetailModal",
    "components/diner/ItemDetailModal.tsx",
    "visual",
    true,
    true,
    "covered",
    "Item detail sheet.",
  ],
  [
    "PhoneCaptureModal",
    "components/diner/PhoneCaptureModal.tsx",
    "visual",
    true,
    true,
    "covered",
    "Phone capture sheet.",
  ],
  [
    "CartScreen",
    "components/diner/CartScreen.tsx",
    "screen",
    true,
    true,
    "partial",
    "Screen pattern documented; live migration deferred.",
  ],
  [
    "BillView",
    "components/diner/BillView.tsx",
    "screen",
    true,
    true,
    "partial",
    "Payment pattern documented; live migration deferred.",
  ],
  [
    "SplitBillModal",
    "components/diner/SplitBillModal.tsx",
    "visual",
    true,
    true,
    "covered",
    "Split setup sheet.",
  ],
  [
    "SplitPartPage",
    "components/diner/SplitPartPage.tsx",
    "screen",
    true,
    true,
    "partial",
    "Participant payment pattern.",
  ],
  [
    "DinerShell",
    "components/diner/DinerShell.tsx",
    "screen",
    true,
    true,
    "covered",
    "Diner layout shell.",
  ],
  [
    "CartContextProvider",
    "components/diner/CartContextProvider.tsx",
    "provider",
    true,
    false,
    "supporting",
    "Behavior provider, not a visual component.",
  ],
  [
    "BillScreenClient",
    "components/diner/BillScreenClient.tsx",
    "client",
    true,
    false,
    "supporting",
    "Route client wrapper; visual patterns are covered by BillView and flow specs.",
  ],
  [
    "DINER tokens",
    "components/diner/ui/diner-tokens.ts",
    "token",
    true,
    false,
    "supporting",
    "Live product-facing token bridge for future diner UI migration.",
  ],
].map(([name, path, kind, documented, showcased, migrationStatus, notes]) => ({
  name,
  path,
  kind,
  documented,
  showcased,
  migrationStatus,
  notes,
})) as ComponentCoverage[];
