import type { ComponentVariant } from "../types";

export const sheetComponentVariants: ComponentVariant[] = [
  {
    component: "BottomSheet",
    variant: "standard",
    group: "Sheets",
    surface: "diner-ordering",
    states: ["default", "loading", "error"],
    tokensUsed: [
      "radius/sheet",
      "surface/elevated",
      "shadow/sheet",
      "black-alpha.40",
    ],
    anatomy: [
      "Overlay",
      "Sheet",
      "Drag handle",
      "Scrollable body",
      "Optional fixed footer",
    ],
    accessibility: [
      "Trap focus",
      "Expose title and description",
      "Support keyboard dismissal",
    ],
    usage: "Reusable sheet container for diner task flows.",
    avoid: "Avoid edge-to-edge sheets on normal mobile widths.",
    exampleClassName:
      "rounded-[20px] bg-white shadow-[0_-4px_24px_rgba(0,0,0,0.10)]",
    status: "stable",
  },
  {
    component: "ItemDetailModal",
    variant: "with-fixed-cta",
    group: "Sheets",
    surface: "diner-ordering",
    states: ["default", "disabled", "loading", "error"],
    tokensUsed: [
      "radius/sheet",
      "space/sheet-padding",
      "layout/sheet-max-height",
    ],
    anatomy: [
      "Media",
      "Title",
      "Description",
      "Modifiers",
      "Note",
      "Quantity",
      "Fixed CTA",
    ],
    accessibility: [
      "Required modifiers need text labels",
      "Content must remain visible above CTA",
    ],
    usage: "Viewing and adding menu items.",
    avoid:
      "Avoid close buttons over media; drag handle is enough for diner sheets.",
    status: "stable",
  },
  {
    component: "PhoneCaptureModal",
    variant: "phone-input",
    group: "Sheets",
    surface: "diner-ordering",
    states: ["default", "error", "loading"],
    tokensUsed: ["DinerInput", "radius/sheet", "button/primary.background"],
    anatomy: ["Title", "Helper text", "Phone input", "Fixed/primary action"],
    accessibility: ["Input label and helper text must be connected"],
    usage: "Capturing phone for receipts and order updates.",
    avoid: "Avoid collecting phone without explaining why.",
    status: "stable",
  },
  {
    component: "SplitBillModal",
    variant: "split-controls",
    group: "Sheets",
    surface: "diner-ordering",
    states: ["default", "selected", "loading", "error"],
    tokensUsed: ["SegmentedTabs", "Payment Card", "radius/sheet"],
    anatomy: ["Split mode", "Participant count", "Link/status", "CTA"],
    accessibility: ["Mode changes should preserve focus and labels"],
    usage: "Equal, item-based, and custom split setup.",
    avoid: "Avoid hidden split state changes without labels.",
    status: "stable",
  },
];
